### ISSUE TITLE
How to get status of purchase?

### ISSUE THREAD

**Issue by skurvish** [NobrainerWeb/omnipay-quickpay#11]
Using this api I can get a link and redirect to it. I can make the payment and am redirected back to my returnUrl. How do I then get the status of the transaction?

Of all the test cards I have tried when they are processed I get redirected to my returnUrl. If for any reason the card is rejected Quickpay simply advises that there has been an error, try again. It doesn't really tell me what the error is. If I cancel then I am redirected to my cancelUrl. I would like to be able to get some information on the reason for the rejection so I can log it.

Any help would be appreciated.

**Comment by NobrainerWeb** [comment]
I'm not sure what you are asking; but as far as i remember you define a callback url, that quickpay will send an async "update" to.

**Comment by skurvish** [comment]
I do get the callback OK but I am not sure what I need to do to verify the purchase with quickpay. In the quickpay manager the transactions are showing as unverified, that the cllback has failed. I have to assume there is something I have to do in the callback to notify quickpay that the callback was successful. I have tried calling CompletPurchase and Capture but neither of them see to verify the transactiobn with Quickpay. That is where I am stuck.

Any pointers greatly appreciated.

**Comment by skurvish** [comment]
Never mind, I found the problem. I do indeed need to call the CaptureRequest in the callback. I was missing a parameter which I found in the response data.

Thanks.

**Comment by skurvish** [comment]
I spoke to soon. The CaptureRequest is not clearing the callback failure, not sure why. The callback is being called and in this callback I am calling the Capture function. I am doing this because if I attempt a refund without having performed the Capture the refund fails, stating that the transaction has not been captured.

So, I am still at a loss as to how to verify the purchase so the callback status is OK rather than failed.

Hope you can help.

**Comment by skurvish** [comment]
OK, solved this issue. I needed to process two types of callbacks, a continue and a complete. I was processing the Complete but not returning correct status, i.e. I was doing a redirect to another page which gives Quickpay the wrong http status. So now on Complete I simply ignore it and just return, and I do the rest of my processing in the Continue callback.

**Comment by NobrainerWeb** [comment]
Glad you figured it out :-)
