### ISSUE TITLE
Token payments?

### ISSUE THREAD

**Issue by simplenotezy** [NobrainerWeb/omnipay-quickpay#6]
Does it support token billing?

https://github.com/thephpleague/omnipay#token-billing

**Comment by sanderha** [comment]
Unfortunately it does not (yet), as we have not had a use case for this. You are very welcome to create a PR though ;)

**Comment by simplenotezy** [comment]
Hmm - I wonder if we understand each other correctly.

I would like to be able to charge a subscriber (e.g. when user enter his card information, this data is stored, and then we'll be able to charge the user without having to involve the user)

**Comment by sanderha** [comment]
I think you are just referring to normal subscription functionality at Quickpay. This functionality has been implemented in this Omnipay Gateway, even though theres no official omnipay API for subscriptions
